name: Update Snake

on:
  # Executa diariamente à meia-noite
  schedule:
    - cron: "0 0 * * *"
  
  # Permite executar manualmente
  workflow_dispatch:
  
  # Executa quando você faz push no main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Snake Animation
      uses: Platane/snk@v3
      with:
        github_user_name: SimoneFrez
        outputs: |
          github-contribution-grid-snake.svg
          github-contribution-grid-snake-dark.svg?palette=github-dark
    
    - name: Push to output branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: output
        keep_files: true
