name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Roda diariamente à meia-noite
  workflow_dispatch:      # Permite executar manualmente
  push:
    branches:
      - main             # Roda quando você faz push no main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: SimoneFrez  # ALTERE AQUI: seu username
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit and push if changed
        uses: EndBug/add-and-commit@v9
        with:
          author_name: snake-bot
          author_email: snake-bot@users.noreply.github.com
          message: "Generate contribution snake"
          add: "dist/"
          push: true
